Three trees in Flutter added
zuhlke/engineering-posts pull request #48
Opened 2023-05-28 17:02 UTC by gabduss

2023-05-30 11:04 UTC, lehmamic requested changes
Minimum add the ignore blog post marker. Please check it with a spellchecker next time.

2023-05-30 11:04 UTC, lehmamic commented on drafts/three-trees-in-flutter.md
> +In conclusion, the Widget tree, Element tree, and RenderObject tree are three interconnected trees in Flutter that are vital for constructing and rendering UI components efficently. The Widget tree r
```suggestion
In conclusion, the Widget tree, Element tree, and RenderObject tree are three interconnected trees in Flutter that are vital for constructing and rendering UI components efficiently. The Widget tree represents the hierarchical structure of immutable Widgets that describe the UI elements. RenderObjects handle the rendering, while Elements are responsible for the lifecycle and connect the Widget tree with the RenderObject tree.
```

2023-05-30 11:04 UTC, lehmamic commented on drafts/three-trees-in-flutter.md
> +| Responsibilities | - Holds configuration | - Responsible for lifecycle<br> - Holds state of StatefulWidgets<br> - Connects Widgets with RenderObjects | - Responsible for rendering |
Use markdown syntax instead of html

2023-05-30 11:04 UTC, lehmamic commented on drafts/three-trees-in-flutter.md
> +publishAs: gabduss
Make sure your user name exists on hasnode

2023-05-31 18:14 UTC, gabduss commented
> Minimum add the ignore blog post marker. Please check it with a spellchecker next time.

Hi Michael, thank you very much for the review. I installed Grammarly and found a few more mistakes. Sorry for the inconvenience.

2023-06-05 06:51 UTC, merged